name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
 # firebase_auth: ^3.0.2
 # firebase_core: ^1.5.0
  flutter:
    sdk: flutter
 ## google_sign_in: ^5.0.7
  meta: ^1.3.0
  ###very_good_analysis: ^2.4.0
  cache:
    path: ../cache
  sqflite: ^2.0.2
  localstorage: ^4.0.0+1
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  
dev_dependencies:
  json_annotation: ^4.4.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  test: ^1.17.0