name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
 # firebase_auth: ^3.0.2
 # firebase_core: ^1.5.0
  flutter:
    sdk: flutter
 ## google_sign_in: ^5.0.7
  http: ^0.13.4
  meta: ^1.3.0
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  user_repository:
    path: ../user_repository
  encrypt: ^5.0.1
  jwt_io: ^1.1.6





dev_dependencies:
  build_runner: ^2.1.8
  mocktail: ^0.2.0
  json_serializable: ^6.1.5
  test: ^1.17.0 